### ISSUE TITLE
How is 

### ISSUE THREAD

**Issue by MichaelZhouwang** [hanxiao/bert-as-service#144]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?
How is the bert-as-service actually deal with using own tokenizer? For english sentences, if I feed a word that is not in the original vocabulary and take is as an token. Then how does the model return the embedding in the pooling_layer for me? Is the embedding for these word pieces get averaged? Or is there any other post-processing? THANKS for your help!

**Comment by MichaelZhouwang** [comment]
> > For english sentences, if I feed a word that is not in the original vocabulary and take is as an token. Then how does the model return the embedding in the pooling_layer for me?
> 
> Depending on your setting on `-pooling_strategy` and `-pooling_layer`, see:
> https://github.com/hanxiao/bert-as-service#q-what-are-the-available-pooling-strategies
> https://github.com/hanxiao/bert-as-service#q-so-which-layer-and-which-pooling-strategy-is-the-best
> https://github.com/hanxiao/bert-as-service#server-side-configs
> 
> > Is the embedding for these word pieces get averaged?
> 
> By default yes, see
> https://github.com/hanxiao/bert-as-service#server-side-configs

Thanks a lot. However what I mean is not the pooling strategy of the input sequence, but for one token which is not in default vocabulary but treated as one token by setting is_tokenized=True. For example:
embedded = bc.encode(['I', 'anticipate', 'that'], is_tokenized=True) with pooling strategy = NONE. In this sentence, I try to get the embedding of 'anticipate', is this embedding calculated by averaging the embedding of anti, ##ci, and ##pate which are original wordpieces of anticipate? Thanks!!

**Comment by hanxiao** [comment]
@Colanim Since 1.5.5 `bert-as-service` supports customized Tokenization (see: https://github.com/hanxiao/bert-as-service#using-your-own-tokenizer). 

As for @MichaelZhouwang :
1. You should use `bc.encode([['I', 'anticipate', 'that']], is_tokenized=True)`, note it's `[[]]` not `[]` as in your OP.
2. When you set `pooling_strategy=NONE` on the server side, the server won't perform any pooling strategy, but return a `[batch_size, max_seq_len, 768]` tensor as it is.
3. When you call the server via `bc.encode(is_tokenized=True)` from the client, you are telling the server to **respect** your input as tokenized and **do not** tokenize your words again. Thus there are two possibilities:

- (a) `anticipate` is in server's vocabulary. All good, you get the avg. of `I`, `anticipate`, `that` when using `pooling_strategy=REDUCE_MEAN` for instance.
- (b) `anticipate` is *not* in the server's vocabulary, this word is marked as `<UNK>` and you get the avg. of `I`, `<UNK>`, `that` when using `pooling_strategy=REDUCE_MEAN` for instance.
