### ISSUE TITLE
How to get lower dimentions of word embedding?

### ISSUE THREAD

**Issue by zysNLP** [hanxiao/bert-as-service#176]
Thank you very much! I use your serving for my work to embed words,but 768 dimension seems too large for my computer to train my model. 
I see you replied someone these sentences before: "if you want 256-dimensional vector, either add a dense(num_units=256) then train on some downstream task, or do subsampling directly in the feature space (make sense if your goal is to build a random forest)"
As you talked about reducing dimensions above. Can you explain the solution in detail? what does "Add a dense" mean? Where can we connect the dense like this? Also the sentence you said: "subsampling directly in the feature space ",I don't quite understand this, could you explain it in a little more detail?

**Comment by Colanim** [comment]
Connect the dense network after the output of the Transformer of BERT.

So basically, you will have to use bert-as-service with the parameter `pooling_strategy` to `None` in order to receive the output of transformer.

Then you use these vectors as input of a fully connected network, with an output size of 256. And here you go, you have your vectors of size 256. Of course you need to train this dense network on a task.

**Comment by hanxiao** [comment]
cl
