### ISSUE TITLE
how to start dashboard

### ISSUE THREAD

**Issue by policeme** [hanxiao/bert-as-service#243]
@hanxiao I want to start the dashboard, but I didn't find in README.md, can you tell me.

**Comment by hanxiao** [comment]
let me check later. The dashboard may not work normally due to the recent update.

**Comment by policeme** [comment]
@hanxiao  if you finish this work, please tell me, thx!

**Comment by policeme** [comment]
@hanxiao did u finish this work?

**Comment by policeme** [comment]
@hanxiao did you finish this work?, hope you can reply me.

**Comment by hanxiao** [comment]
Please, do not push. This is not how OSS works. I also have my own daily agenda and priority. Hope you understand and respect that.

Always remember in an open-source community, everyone (including you) has the freedom to modify the code and work independently.

**Comment by policeme** [comment]
sorry, It's my fault.

**Comment by hanxiao** [comment]
fyi, this issue is fixed in #252, the new feature is available in 1.8.3.

To start a dashboard, make sure you start bert-as-service with `bert-serving-start -http_port xxxx -model_dir ...` and then open [index.html](https://github.com/hanxiao/bert-as-service/blob/master/plugin/dashboard/index.html) in your browser (and of course you need CSS and JS files as well). Change the URL (with port!) in the text box on the top-right. You should see the server statistics immediately.

Play with the javascript to customize the layout or behavior of the dashboard by yourself.
