### ISSUE TITLE
how to compress bert model

### ISSUE THREAD

**Issue by 34127chi** [hanxiao/bert-as-service#268]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version:1.10.0
- Python version:3.6.7
- `bert-as-service` version:1.8.0 
- GPU model and memory:None
- CPU model and memory:16g

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir bert_model_path -cpu 
```

and calling the server via:
```python
bc = BertClient()
bc.encode()
```

Then this issue shows up:

we wanna apply the bert_as_service module in production, however we found it can't meet our demand, because it cost huge memory(2g) and it takes 100ms to encode a sentence(no gpu).

my question:  do you think about compressing the bert model or can you give me a hint about that?

thanks.

**Comment by hanxiao** [comment]
First of all, please note that `bert-as-service` is not designed for edge computing. The `BertServer` is computational intensive and therefore should rest on a more powerful machine rather than an edge device (e.g. raspberry pi). On the other hand, `BertClient` is very lightweight and can be deployed on less powerful machine. I can totally understand the need and interest of putting the server side on the edge device, but again [`bert-as-service` isn't designed for such case](https://hanxiao.github.io/2019/01/02/Serving-Google-BERT-in-Production-using-Tensorflow-and-ZeroMQ#Serving-with-low-latency).

`bert-as-service` is optimized for scalability and therefore has reduced the memory footprint significantly. You can further reduce the memory consumption and speed up the inference [by using `-fp16`](https://bert-as-service.readthedocs.io/en/latest/source/server.html#Serving%20Configs), provide that your machine supports half precision instruction (otherwise you will get extremely slow result).

Finally `bert-as-service` implements model compression on the engineering-level but not algorithmic-level.

**Comment by hanxiao** [comment]
By tuning `-pooling_layer`, you may use [lower level representation as well to speedup the inference](https://github.com/hanxiao/bert-as-service/#speed-wrt-pooling_layer).
