### ISSUE TITLE
Too many concurrent connections!Try to increase the value of "max_concurrency", currently =10

### ISSUE THREAD

**Issue by HorningFeng** [hanxiao/bert-as-service#294]
When I use Spark to calling bert server I get this.
![image](https://user-images.githubusercontent.com/13342892/55068973-fae71500-50bd-11e9-938e-5b2197223210.png)

How can I set the max_concurrency? Is it a conf which belongs to server, or client?

Could you provide some advice about huge-size data to inferencing bert model?
thx very much.

**Comment by hanxiao** [comment]
use `http_max_connect ` in https://bert-as-service.readthedocs.io/en/latest/source/server.html#server-side-api

That said, this wont happen unless you have 10 *concurrent* http requests. So your problem is not increasing this value, but using it in a correct way.

I notice that your job has size only 1, meaning `batch_size=1`, aka one sentence a time. This is really bad and shouldn't happen unless you are serving real users in production (where the traffic is sparse and out of your control).

Rule of thumb, you should always **send a batch** to the server. A batch can be as large as 1 million sentences, but no worry, just send it to the server. The sever already implements a sophisticated batching scheme to handle nearly all cases.

*Do not* split a batch into a set of single-sentence-batches and send to the server. This won't give you any benefit.
