### ISSUE TITLE
ubuntu bert-service 进程在处理一部分数据后就卡住不动了

### ISSUE THREAD

**Issue by JemmryXin** [hanxiao/bert-as-service#482]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`?
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:
在处理8w条数据的时候，处理到一半就停住了
...

**Comment by superman-hulin** [comment]
请问你现在这个问题解决了吗

**Comment by HuimengZhang** [comment]
同样有这样的问题，工程挺好的，但不维护的吗？

**Comment by hanxiao** [comment]
> 同样有这样的问题，工程挺好的，但不维护的吗？

@HuimengZhang 

Please describe the problem like step-by-step. How to reproduce the problem? Otherwise, it doesn't help anybody by posting "not working". You know that but still you choose to simply repeat the meaningless reply. It makes one hard to take problem seriously.

Please note that this is an open-source software, which means you have access to the code and you can fix the problem by yourself. So please don't say "why is nobody maintaining it?"
